In [77]:
import numpy as np

In [78]:
np.random.seed(45)

In [79]:
rating = np.random.randint(1,6, size=(100,4))
rating

array([[4, 4, 5, 1],
       [4, 5, 2, 1],
       [2, 2, 1, 1],
       [5, 3, 5, 1],
       [5, 2, 5, 1],
       [3, 5, 5, 2],
       [2, 5, 3, 4],
       [1, 1, 2, 4],
       [4, 3, 1, 5],
       [2, 1, 1, 2],
       [3, 4, 1, 1],
       [4, 3, 3, 5],
       [2, 3, 1, 2],
       [1, 1, 1, 1],
       [4, 5, 1, 4],
       [2, 4, 5, 2],
       [4, 4, 3, 5],
       [2, 2, 2, 4],
       [2, 5, 3, 3],
       [2, 5, 4, 5],
       [5, 2, 3, 4],
       [4, 4, 1, 5],
       [5, 2, 4, 3],
       [4, 2, 1, 3],
       [4, 4, 2, 4],
       [2, 5, 5, 3],
       [3, 4, 2, 4],
       [4, 2, 2, 2],
       [5, 1, 3, 3],
       [2, 3, 5, 2],
       [5, 3, 3, 4],
       [3, 4, 3, 4],
       [4, 4, 5, 3],
       [1, 3, 2, 3],
       [5, 2, 5, 5],
       [4, 5, 4, 3],
       [5, 2, 4, 1],
       [4, 5, 1, 3],
       [5, 1, 4, 5],
       [3, 1, 2, 2],
       [2, 3, 5, 5],
       [1, 1, 3, 1],
       [2, 5, 5, 5],
       [4, 3, 3, 4],
       [4, 2, 3, 1],
       [1, 1, 2, 4],
       [5, 5, 1, 3],
       [3, 3,

In [80]:
maximum = rating.max()
minimum = rating.min()
normalize = (rating-minimum) / (maximum-minimum)
print(f"Normalized ratting of employee :-\n{normalize}")

Normalized ratting of employee :-
[[0.75 0.75 1.   0.  ]
 [0.75 1.   0.25 0.  ]
 [0.25 0.25 0.   0.  ]
 [1.   0.5  1.   0.  ]
 [1.   0.25 1.   0.  ]
 [0.5  1.   1.   0.25]
 [0.25 1.   0.5  0.75]
 [0.   0.   0.25 0.75]
 [0.75 0.5  0.   1.  ]
 [0.25 0.   0.   0.25]
 [0.5  0.75 0.   0.  ]
 [0.75 0.5  0.5  1.  ]
 [0.25 0.5  0.   0.25]
 [0.   0.   0.   0.  ]
 [0.75 1.   0.   0.75]
 [0.25 0.75 1.   0.25]
 [0.75 0.75 0.5  1.  ]
 [0.25 0.25 0.25 0.75]
 [0.25 1.   0.5  0.5 ]
 [0.25 1.   0.75 1.  ]
 [1.   0.25 0.5  0.75]
 [0.75 0.75 0.   1.  ]
 [1.   0.25 0.75 0.5 ]
 [0.75 0.25 0.   0.5 ]
 [0.75 0.75 0.25 0.75]
 [0.25 1.   1.   0.5 ]
 [0.5  0.75 0.25 0.75]
 [0.75 0.25 0.25 0.25]
 [1.   0.   0.5  0.5 ]
 [0.25 0.5  1.   0.25]
 [1.   0.5  0.5  0.75]
 [0.5  0.75 0.5  0.75]
 [0.75 0.75 1.   0.5 ]
 [0.   0.5  0.25 0.5 ]
 [1.   0.25 1.   1.  ]
 [0.75 1.   0.75 0.5 ]
 [1.   0.25 0.75 0.  ]
 [0.75 1.   0.   0.5 ]
 [1.   0.   0.75 1.  ]
 [0.5  0.   0.25 0.25]
 [0.25 0.5  1.   1.  ]
 [0.   0.   0.5  0.  ]


In [81]:
average_rating = rating.mean(axis=1)
print(f"Employee average rating is:- \n {average_rating}")

Employee average rating is:- 
 [3.5  3.   1.5  3.5  3.25 3.75 3.5  2.   3.25 1.5  2.25 3.75 2.   1.
 3.5  3.25 4.   2.5  3.25 4.   3.5  3.5  3.5  2.5  3.5  3.75 3.25 2.5
 3.   3.   3.75 3.5  4.   2.25 4.25 4.   3.   3.25 3.75 2.   3.75 1.5
 4.25 3.5  2.5  2.   3.5  2.75 3.5  2.75 1.5  3.5  3.   2.25 3.   3.5
 3.   3.   3.75 2.75 3.25 3.75 2.75 3.75 2.25 3.25 3.5  3.75 2.5  1.5
 3.   3.   1.5  2.25 1.75 3.25 3.5  3.   1.75 2.25 3.5  2.25 4.   1.75
 3.   3.   2.75 3.75 1.5  3.25 3.   3.5  4.   4.25 3.25 3.25 2.5  3.25
 2.25 3.5 ]


In [82]:
company_mean = average_rating.mean()
print(f"Company average rating is:- \n {company_mean}")

above_company_mean = np.where(average_rating>company_mean)
print(f"Employee with greater mean than company mean:- \n{above_company_mean}")

Company average rating is:- 
 3.0025
Employee with greater mean than company mean:- 
(array([ 0,  3,  4,  5,  6,  8, 11, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25,
       26, 30, 31, 32, 34, 35, 37, 38, 40, 42, 43, 46, 48, 51, 55, 58, 60,
       61, 63, 65, 66, 67, 75, 76, 80, 82, 87, 89, 91, 92, 93, 94, 95, 97,
       99]),)
