In [26]:
import numpy as np

In [27]:
np.random.seed(1)
vitals = np.random.randint(60, 100, size=(60, 24))
print(vitals)

[[97 72 68 ... 74 64 83]
 [83 90 92 ... 64 84 72]
 [86 76 78 ... 98 68 92]
 ...
 [95 98 68 ... 77 97 80]
 [83 78 75 ... 69 81 60]
 [72 92 77 ... 88 63 92]]


In [28]:
average_heart_rate = np.mean(vitals, axis=1)
print(f"Hourly average heart rate:- \n{average_heart_rate.round()}")

Hourly average heart rate:- 
[75. 74. 81. 76. 78. 80. 80. 79. 80. 82. 79. 81. 81. 80. 84. 85. 79. 76.
 82. 79. 84. 84. 80. 78. 81. 82. 82. 83. 79. 81. 83. 80. 76. 75. 75. 76.
 83. 77. 78. 80. 83. 79. 79. 78. 81. 81. 80. 80. 78. 81. 78. 79. 83. 74.
 82. 81. 80. 83. 77. 80.]


In [29]:
abnormal_value = vitals[(vitals < 60) | (vitals > 100)]
print(f"Detected Abnormal reading out of range are :- {abnormal_value}")

Detected Abnormal reading out of range are :- []


In [35]:
vitals = vitals.astype(float)
vitals[5,2] = np.nan
vitals[0,1] = np.nan
for i in range(1, vitals.shape[1]):
    mask = np.isnan(vitals[:,i])
    print(mask)



[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False]
[False False False False False  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False 