In [1]:
import numpy as np

In [2]:
np.random.seed(1)
course_data = np.random.randint(0, 61, size=(14, 6))
print(course_data)

[[37 43 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 45 60  6 25 50]
 [20 37 18 20 11 60]
 [42 28 29 14 50  4]
 [23 23 41 49 55 30]
 [32 22 13 41  9  7]
 [22 57  1  0 60 17]
 [ 8 24 13 51 47 42]
 [57  8 30  7  3  6]
 [21 49 57  3  4 24]
 [49 43 12 26 52 16]
 [45 51 41 18 15  0]
 [ 4 25 47 34 23  7]]


In [3]:
time_per_course = course_data.sum(axis=0)
print(time_per_course)

[372 470 374 293 364 286]


In [28]:
threshold = time_per_course.mean()
print(threshold)

359.8333333333333


In [32]:
engagement = np.argsort(time_per_course)[::-1]
print(engagement)
for rank, idx in enumerate(engagement):
    print(f"Time engaged on course {idx+1} is {time_per_course[idx]}")

[1 2 0 4 3 5]
Time engaged on course 2 is 470
Time engaged on course 3 is 374
Time engaged on course 1 is 372
Time engaged on course 5 is 364
Time engaged on course 4 is 293
Time engaged on course 6 is 286
