In [55]:
import numpy as np

In [56]:
# Set 3 (Weather Monitoring System)
# NumPy (Intermediate)
#  A weather station stores hourly temperature readings for 7 days in a NumPy array of shape (7, 24).
# Task:
# Find the daily maximum and minimum temperature
#
#
# Identify the day with the largest temperature variation
#
# Replace outliers beyond ±2 standard deviations with the mean temperature


In [57]:
np.random.seed(1)
data = np.random.randint(-2, 42, size=(7,24))
print(data)

[[35 41 10  6  7  9  3 13 -2 14 -1 10  5  4 23 18 35 16 18  9 40 26 27 12]
 [ 2 21 21 39 28 30 20 11 39  7  5 20 -1 -2 15  6 22 11 40  6 28  5  1  4]
 [19  1  2 22 41 10 24 14 39 16 13 -2  2 23 32 21  5 24 23 38 20  7  1 37]
 [21 34 25 35 17 36  6 30 32  8 21 13 21 23  5 26  8 30 22 21 -1 11  1 -2]
 [11  4 19  4  0 10 25 19  9  5 11  6  9 10 41 18 28 34 37  5  2 16 30 11]
 [ 8 21 15  5 22  8 26 18 30 10 -1 28 39 22 16 31  0 26 37 32  8 30 39 16]
 [20  4  0  5 37 13  3 15 40 18 20 35 11 31 18  8 30 23 19 37 30 17 23 12]]


In [58]:
min_temp = data.min(axis=1)
print(f"Minimum temperature of each day:- {min_temp}")
max_temp = data.max(axis=1)
print(f"Maximum temperature of each day:- {max_temp}")

Minimum temperature of each day:- [-2 -2 -2 -2  0 -1  0]
Maximum temperature of each day:- [41 40 41 36 41 39 40]


In [59]:
temp_var = max_temp - min_temp
print(f"Variation in temperature of each day:- \n{temp_var}")
print(f"Day '{temp_var.argmax() + 1}' has the largest temperature variation of the day")

Variation in temperature of each day:- 
[43 42 43 38 41 40 40]
Day '1' has the largest temperature variation of the day


In [61]:
mean_temp = data.mean()
std_temp = data.std()

lo = mean_temp - 2*std_temp
hi = mean_temp + 2*std_temp

outliner_mask = (data < lo) | (data > hi)
data_cleaned = np.where(outliner_mask, mean_temp, data)
print(data_cleaned)


[[35. 41. 10.  6.  7.  9.  3. 13. -2. 14. -1. 10.  5.  4. 23. 18. 35. 16.
  18.  9. 40. 26. 27. 12.]
 [ 2. 21. 21. 39. 28. 30. 20. 11. 39.  7.  5. 20. -1. -2. 15.  6. 22. 11.
  40.  6. 28.  5.  1.  4.]
 [19.  1.  2. 22. 41. 10. 24. 14. 39. 16. 13. -2.  2. 23. 32. 21.  5. 24.
  23. 38. 20.  7.  1. 37.]
 [21. 34. 25. 35. 17. 36.  6. 30. 32.  8. 21. 13. 21. 23.  5. 26.  8. 30.
  22. 21. -1. 11.  1. -2.]
 [11.  4. 19.  4.  0. 10. 25. 19.  9.  5. 11.  6.  9. 10. 41. 18. 28. 34.
  37.  5.  2. 16. 30. 11.]
 [ 8. 21. 15.  5. 22.  8. 26. 18. 30. 10. -1. 28. 39. 22. 16. 31.  0. 26.
  37. 32.  8. 30. 39. 16.]
 [20.  4.  0.  5. 37. 13.  3. 15. 40. 18. 20. 35. 11. 31. 18.  8. 30. 23.
  19. 37. 30. 17. 23. 12.]]
